src/set_get.jl

This PR adds `@inbounds` and `@propagate_inbounds` in appropriated places to optimize the performance.
PR:
```julia
julia> using ComponentArrays
julia> c = (a=2, b=[1, 2]);
julia> x = ComponentArray(a=1, b=[2, 1, 4], c=c)
ComponentVector{Float64}(a = 1.0, b = [2.0, 1.0, 4.0], c = (a = 2.0, b = [1.0, 2.0]))
julia> foo(x) = x.a
foo (generic function with 1 method)
julia> @code_native debuginfo=:none foo(x)
.text
movq    (%rdi), %rax
movq    (%rax), %rax
vmovsd  (%rax), %xmm0           # xmm0 = mem[0],zero
retq
nopl    (%rax,%rax)
```
Master:
```julia
julia> @code_native debuginfo=:none foo(x)
.text
movq    (%rdi), %rdi
cmpq    $0, 8(%rdi)
je      L18
movq    (%rdi), %rax
vmovsd  (%rax), %xmm0           # xmm0 = mem[0],zero
retq
L18:
pushq   %rbp
movq    %rsp, %rbp
movq    %rsp, %rax
leaq …
```

Add at inbounds and propagate_inbounds

---

Project.toml
src/show.jl

```
julia> foo(u0) = sqrt(-u0[1])
foo (generic function with 1 method)
julia> foo(u0)
ERROR: DomainError with -2.8e6:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
[1] throw_complex_domainerror(::Symbol, ::Float64) at ./math.jl:33
[2] sqrt at ./math.jl:573 [inlined]
[3] foo(::ComponentArray{Float64,1,Array{Float64,1},Tuple{Axis{(outdoor_hex = ViewAxis(1:20, Axis((Ps = 1:4, hs = 5:8, Ms = 9:12, Us = 13:16, TWalls = 17:20))), indoor_hex = ViewAxis(21:40, Axis((Ps = 1:4, hs = 5:8, Ms = 9:12, Us = 13:16, TWalls = 17:20))))}}}) at ./REPL[481]:1
[4] top-level scope at REPL[482]:1
julia> Base.show(io::IO, ::Type{<:ComponentArray}) = print(io, "ComponentArray")
julia> foo(u0)
ERROR: DomainError with -2.8e6:
sqrt will only return a …
```

Less verbose type printing in stacktrace

---

src/broadcasting.jl

This solves #51, but might defeat the purpose of why that method was introduced in the first place?

Respect broadcasting of functions that changes the eltype

---

Project.toml
src/componentarray.jl

`RecursiveFactorization.lu` should work:
```julia
julia> using RecursiveFactorization, ComponentArrays, BenchmarkTools
julia> A = rand(20,20);
julia> CA = ComponentArray(A, (Axis(a = 1, b = 2:5, c= 6:20), Axis(d = 1:11, e = 12:20)))
20×20 ComponentMatrix{Float64} with axes Axis(a = 1, b = 2:5, c = 6:20) × Axis(d = 1:11, e = 12:20)
0.792297   0.920946    0.787967   0.44453    0.372399  0.829221   0.926357   0.940149   0.217544    …  0.884185   0.500896   0.437198     0.523697   0.775704    0.866969    0.647117   0.197122
0.51889    0.0850669   0.309129   0.800278   0.520421  0.0837537  0.0819355  0.610569   0.619184       0.0469312  0.0461996  0.000108896  0.447549   0.780642    0.100468    0.824336   0.930264
0.86085    0.116267    0.141935   0.830085   0.826916  0.755773   0.511896 …
```

Allow ArrayInterface 3, support ArrayInterface

---

Project.toml

I haven't actually looked at the code to see if anything else is needed,
lets see what CI says

Allow ChainRulesCore 1.0

---

src/compat/diffeqbase.jl

The current project.toml claims compatibility for julia "1".
The function call "p(x, getdata(A), b, update_matrix; tol, kwargs...)"
as shorthand for  "p(x, getdata(A), b, update_matrix; tol=tol, kwargs...)"
only became valid in Julia 1.5.  Compare
https://docs.julialang.org/en/v1.4/manual/functions/#Keyword-Arguments-1
with
https://docs.julialang.org/en/v1.5/manual/functions/#Keyword-Arguments
which adds the paragraph starting with "When a bare identifier or dot
expression occurs after a semicolon,"

Don't use syntactic sugar only available in julia >= 16

---

src/compat/chainrulescore.jl

Replaces the pullback for axes argument with NoTangent().

Updated ChainRulesCore.rrule

---

src/compat/scimlbase.jl
test/diffeq_test/diffeq_tests.jl

I was unable to symbolically index the solutions to differential equation solutions. I've changed `SciMLBase.getsyms` method to fix this and adding some test. 
The plotting functionality is also maintained (lines are labelled with the correct symbols). I don't know how to test this though. It's still not possible to do something like `plot(sol, vars=(:x,))`.

changing sciml base indexing and adding test

---

src/array_interface.jl

The fallback of `similar(A,0,0)` gives a `Matrix` instead of a ComponentMatrix. This fixes that to make the types correct for LU-factorization returns. Fixes https://github.com/SciML/DifferentialEquations.jl/issues/849

Overload lu_instance to it generates LU{ComponentMatrix}

---

Project.toml
src/compat/chainrulescore.jl
src/componentarray.jl
test/autodiff_tests.jl

Speed up NamedTuple-style construction of ComponentArrays.

Slightly faster construction

---

src/componentarray.jl
src/utils.jl

Maybe I misunderstood, `reduce` looks like it's for restoring the type. If the type is determined at the beginning, then there is no need to call `reduce`.
```julia
julia> data_1 = rand(30,20);
julia> data_2 = rand(30,20);
julia> @benchmark ComponentArray(a = $data_1, b = $data_2) # Original
BenchmarkTools.Trial: 8075 samples with 1 evaluation.
Range (min … max):  372.000 μs …   5.988 ms  ┊ GC (min … max):  0.00% … 90.97%
Time  (median):     451.300 μs               ┊ GC (median):     0.00%
Time  (mean ± σ):   615.631 μs ± 819.858 μs  ┊ GC (mean ± σ):  25.07% ± 16.55%
██▄▃▁                                                     ▁ ▁ ▂
█████▇▆▅▃▅▄▄▄▁▃▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅████ █
372 μs        Histogram: log(frequency) by time          5 ms <
Memory estimate: 2.96 MiB, …
```

way faster constructor

---

src/compat/gpuarrays.jl

Currently constructing ComponentArrays on the GPU with for example `ComponentArray(a=CUDA.ones(2,3), b=CUDA.ones(4,5))` fails with an error.
```
ERROR: CuArray only supports element types that are stored inline
```
This fails because constructing the ComponentArray causes the creation of an array of arrays, which is not possible on the GPU. This happens in the `pushcat!` call at line 179 in componentarray.jl:
https://github.com/jonniedie/ComponentArrays.jl/blob/a7d6f7d126c5aeb711b65cf74eff8f8cbbeca5d0/src/componentarray.jl#L178-L182
This pull request fixes the issue by constructing the ComponentArray on the CPU and moving it back to the GPU afterwards.
Fixes #158. Needed for SciML/NeuralPDE.jl#594.

Add constructor for GPUArrays

---

src/axis.jl

I found quite a few invalidations using the following code with Julia v1.8.3:
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.develop("ComponentArrays"); Pkg.add("Trixi")
julia> using SnoopCompileCore; invalidations = @snoopr(using Trixi); using SnoopCompile
julia> length(uinvalidated(invalidations))
1655
julia> trees = invalidation_trees(invalidations)
...
inserting CartesianIndices(ax::Tuple{Vararg{ComponentArrays.CombinedAxis}}) in ComponentArrays at /home/hendrik/.julia/dev/ComponentArrays/src/axis.jl:205 invalidated:
backedges: 1: superseding CartesianIndices(indices::R) where {N, R<:Tuple{Vararg{OrdinalRange{Int64, Int64}, N}}} in Base.IteratorsMD at multidimensional.jl:249 with MethodInstance for CartesianIndices(::Tuple{Vararg{Base.OneTo{Int64}}}) (180 children)
37 …
```

fix invalidations

---

src/array_interface.jl
src/axis.jl
test/runtests.jl

As described in the title, this PR fixes tow indexing issues (#175 and #174) and adds associated tests.
Note: When indexing with zero a zero length tuple or vector of symbols a vector instead of a componentvector is returned which I find inconsistent. I didn't opt to address this in this PR, as I that it is a result of more fundamental choices regarding `_getindex` and the handling of ComponentVectors with flat axes only. I plan to open a separate issue to discuss these.

Fix indexing issues #175 and #174

---

Project.toml
src/array_interface.jl
src/componentarray.jl
test/runtests.jl

The method
```julia
Base.reshape(A::AbstractArray, axs::NTuple{N,<:CombinedAxis}) where {N} = reshape(A, _array_axis.(axs))
```
commits type piracy for empty tuples since `() isa NTuple{N, <:CombinedAxis} where {N}`. This was introduced to fight `OffsetArrays`' type piracy for `reshape. We're going to revert this and only make a method for the splatted version. If someone is hitting an issue related to #123, they need to take it up with OffsetArrays

No reshape piracy

---

Project.toml
src/compat/chainrulescore.jl
test/autodiff_tests.jl

Ensures that the gradient of a CA is of type CA.

Add ProjectTo for CA

---

Project.toml
ext/ComponentArraysConstructionBaseExt.jl
ext/ComponentArraysGPUArraysExt.jl
ext/ComponentArraysRecursiveArrayToolsExt.jl
ext/ComponentArraysReverseDiffExt.jl
ext/ComponentArraysSciMLBaseExt.jl
ext/ComponentArraysStaticArraysExt.jl
src/ComponentArrays.jl

Current naming can cause problems like https://github.com/FluxML/Flux.jl/issues/2242 (note that CA doesn't cause this problem, but it could lead to similar hard-to-debug issues)
Also see discussion in https://github.com/JuliaMath/ChangesOfVariables.jl/pull/13

Fix extension naming

---

Project.toml
src/array_interface.jl
src/axis.jl
src/componentarray.jl
src/similar_convert_copy.jl
test/Project.toml
test/runtests.jl

Fix Vararg warnings

---

Project.toml
src/similar_convert_copy.jl
test/runtests.jl

Make `zero` work correctly for `ComponentVector{Bool}`

---

ext/ComponentArraysGPUArraysExt.jl

Hi,
After the switch to Julia extensions (#192), the methods that are not exported by ComponentArrays are not accessible in the extension source files. This leads to an undefined reference when calling `recursive_eltype` at [line 77](https://github.com/jonniedie/ComponentArrays.jl/blob/97eb9e3db7904ea13b823403d00ddd9e9d6c078f/ext/ComponentArraysGPUArraysExt.jl#L77) in the constructor of ComponentArray on the GPU:
https://github.com/jonniedie/ComponentArrays.jl/blob/97eb9e3db7904ea13b823403d00ddd9e9d6c078f/ext/ComponentArraysGPUArraysExt.jl#L76-L81
This pull request adds the missing import and fixes #209.

Fix `recursive_eltype` not defined when constructing ComponentArray on the GPU

---

NEWS.md
Project.toml
docs/make.jl
docs/src/static_unpack.md
ext/ComponentArraysStaticArraysExt.jl
src/ComponentArrays.jl
src/compat/static_arrays.jl
test/runtests.jl

```julia
julia> using ComponentArrays
julia> ca = ComponentArray(a=5, b=[4, 1], c = [1 2; 3 4], d=(a=2, b=[6, 30.0]))
ComponentVector{Float64}(a = 5.0, b = [4.0, 1.0], c = [1.0 2.0; 3.0 4.0], d = (a = 2.0, b = [6.0, 30.0]))
julia> @static_unpack a, b, c, d = ca
ComponentVector{Float64,SubArray...}(a = 2.0, b = [6.0, 30.0])
julia> a
5.0
julia> b
2-element SVector{2, Float64} with indices SOneTo(2):
4.0
1.0
julia> c
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
1.0  2.0
3.0  4.0
julia> d
ComponentVector{Float64,SubArray...}(a = 2.0, b = [6.0, 30.0])
```

Easily unpack components to static arrays

---

Project.toml
ext/ComponentArraysZygoteExt.jl

Continuing my saga of upstreaming pirated patches from Lux. Zygote + AMDGPU + CAs.jl don't play too well. See https://buildkite.com/julialang/lux-dot-jl/builds/634#018ab9ff-bbcb-47bf-aa05-079929053253/6-4602.
This is mostly a hacky patch, but it fixes it.

Fix Zygote accum for CA in GPU broadcasting

---

Project.toml
src/linear_algebra.jl
test/runtests.jl

MWE:
```julia
julia> y = ComponentArray(a = cu(zeros(2)), b = cu(zeros(2)))
ComponentVector{Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Tuple{Axis{(a = 1:2, b = 3:4)}}}(a = Float32[0.0, 0.0], b = Float32[0.0, 0.0])
julia> x = ComponentArray(a = cu(rand(2)), b = cu(rand(2)))
ComponentVector{Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Tuple{Axis{(a = 1:2, b = 3:4)}}}(a = Float32[0.024100939, 0.77158135], b = Float32[0.40818077, 0.44528246])
julia> axpy!(-1, y, x)  # After the patch
ComponentVector{Float32, ComponentVector{Float32, CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, Tuple{Axis{(a = 1:2, b = 3:4)}}}, Tuple{Axis{(a = 1:2, b = 3:4)}}}(a = Float32[0.024100939, 0.77158135], b = Float32[0.40818077, 0.44528246])
julia> axpy!(-1, y, x)  # Before the patch for CUDA
ERROR: …
```

Write direct dispatches for `axpy!` & `axpby!`

---

Project.toml
ext/ComponentArraysGPUArraysExt.jl

fix #227 
TODO
@jonniedie LMK if you want me to add tests.

add missing `LinearAlgebra` methods on GPU

---

Project.toml
src/array_interface.jl
src/compat/chainrulescore.jl
test/autodiff_tests.jl

1. ProjectTo: Protect against Wrapping a ComponentArray into a ComponentArray
2. Higher Order Derivatives while computing Jacobian of FFJORD (Added a non-lux version of https://github.com/LuxDL/Lux.jl/issues/286)

DiffEqFlux Patches

---

src/componentarray.jl

The new version is 1.5x faster for constructing a ComponentArray with 100 fields each with a 10 element vector.
Benchmarks:
```julia
julia> using ComponentArrays, Chairmarks
Precompiling ComponentArrays
1 dependency successfully precompiled in 1 seconds. 36 already precompiled.
julia> s(i) = Symbol("x"*string(i))
s (generic function with 1 method)
julia> const NT = (;(s(i) => randn(10) for i in 1:100)...);
julia> f() = ComponentArray(NT)
f (generic function with 1 method)
julia> @b f() # PR
28.292 μs (246 allocs: 63.703 KiB)
shell> git checkout main
Switched to branch 'main'
Your branch is up to date with 'upstream/main'.
julia> @b f() # main
42.834 μs (849 allocs: 84.344 KiB)
```
This is part of a journey to make `ComponentArray(x = [1,2,3])` not use mutation so that it is compatible …

Switch from a mutation loop to a generator in a `make_idx` path

---

src/axis.jl
src/show.jl

As I was reviewing the subtypes of `AbstractAxis` to try to get a better understanding of how ComponentArrays work, I couldn't figure out the point of the IdxMap type parameter in ShapedAxis, so I decided to remove it and see what breaks....
But all the tests pass without this type parameter, so maybe we can just remove it? It seems to me that the index mapping is tracked at the level of the axis containing the ShapedAxis. For example, in
```julia
julia> typeof(ComponentArray(a=7, b=rand(2,2)))
ComponentVector{Float64, Vector{Float64}, Tuple{Axis{(a = 1, b = ViewAxis(2:5, ShapedAxis((2, 2), NamedTuple())))}}}
```
the indices of the matrix are tracked by the ViewAxis, not the ShapedAxis.
I changed the supertype from `AbstractAxis{NamedTuple()}` to `AbstractAxis{nothing}` because `nothing` …

Remove unused IdxMap type parameter from ShapedAxis

---

docs/Manifest.toml
docs/Project.toml
docs/make.jl

This enables the automatic writing of an `objects.inv` inventory file (and also gives the documentation a slightly nicer UI).
I'd like to be able to use [DocumenterInterLinks](https://github.com/JuliaDocs/DocumenterInterLinks.jl) to link from my project to the documentation of `CompomentArrays`, and this update would make that easier. See also https://github.com/SciML/RecursiveArrayTools.jl/pull/364, although here you were still using a pinned pre-1.0 version of Documenter. (Actually, so old that even [`DocumenterInventoryWritingBackport`](https://github.com/JuliaDocs/DocumenterInventoryWritingBackport.jl]) doesn't support it anymore.) I tried building locally, and everything seems to work fine with Documenter 1.3.
I didn't touch the CI still using Julia 1.6, although using a more recent …

Update Documenter to 1.3

---

src/axis.jl
test/runtests.jl

Fix multi-symbol indexing when components are matrices

---

src/similar_convert_copy.jl
test/runtests.jl

Ref failures in https://github.com/SciML/SciMLSensitivity.jl/actions/runs/9669459445/job/26676007518?pr=1057

feat: Preserve Indices When Copying Tracked Arrays

---

Project.toml
ext/ComponentArraysTrackerExt.jl
test/Project.toml
test/autodiff_tests.jl

still need to test if this fixes the scimlsensitivity issues.
cc @ChrisRackauckas

fix: restructure of tracked component arrays

---

Project.toml
src/componentarray.jl
test/runtests.jl

Fixes https://discourse.julialang.org/t/no-method-error-reshape-when-solving-ode-with-componentarrays-jl/126342

Fix CombinedAxis fallback reshape on AbstractArray

---

Project.toml
src/axis.jl
test/runtests.jl

[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Currently when calling `vcat` with two `ComponentVector`s, all multi-dimensional components of the *second* argument are flattened:
```
julia> x = ComponentVector(a=rand(Float64, 2, 3, 4), b=rand(Float64, 4, 3, 2))
julia> y = ComponentVector(c=rand(Float64, 3, 4, 2), d=rand(Float64, 3, 2, 4))
julia> xy = vcat(x, y)
julia> size(xy.a)
(2, 3, 4)
julia> size(xy.b)
(4, 3, 2)
julia> size(xy.c)
(24,)
julia> size(xy.d)
(24,)
julia> 
```
This PR fixes that.

Preserve `ShapedAxis` components during `vcat`

---

Project.toml
src/componentarray.jl
test/runtests.jl

upstreamed from Lux.jl. See https://github.com/LuxDL/Lux.jl/issues/1359

fix: component array of empty namedtuple
